development:
  adapter: redis

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") {"redis://red-cdg2du4gqg4123jj6t50:6379"} %>
  # url: <%= ENV.fetch("REDIS_URL") {"redis://localhost:6379/1"} %>
  channel_prefix: chat-app_production
